# Generated by Django 5.0.3 on 2024-06-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-comletiondate']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='comletiondate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
